# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

server:
  standalone:
    enabled: true
    config: |
      ui = true

      listener "tcp" {
        tls_disable = 1
        address = "[::]:8200"
        cluster_address = "[::]:8201"
      }
      storage "file" {
        path = "/vault/data"
      }
  service:
    enabled: true
  dataStorage:
    enabled: true
    size: 10Gi
    storageClass: null
    accessMode: ReadWriteOnce
injector:
  enabled: true
  logLevel: "debug" 
ui:
  enabled: true
  serviceType: LoadBalancer
