# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceRouter
metadata:
  name: frontend
spec:
  routes:
    - match:
        http:
          pathPrefix: "/v2"
      destination:
        prefixRewrite: "/"
        serviceSubset: "v2"
