# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: counting-allow-partition-workload
spec:
  destination:
    name: counting     # in partion called partition-workload
  sources:
   - name: dashboard
     action: allow
     partition: "default"  # dashboard in default admin partition


