global:
  enabled: true
  name: consul-dc2
  domain: consul
  apiVersion: v2
  datacenter: dc2
  image: hashicorp/consul-enterprise:1.16.2-ent
# imageEnvoy: "envoyproxy/envoy-alpine:v1.25.6"   # Pulls the latest supported when unspecified.
# imageConsulDataplane: "hashicorp/consul-dataplane:1.2.1"  # Pulls the latest when unspecified.
# imageK8S: hashicorp/consul-k8s-control-plane:1.2.1
  logLevel: "debug"


  enterpriseLicense:
    secretName: consul-ent-license
    secretKey: key

  dns:
    enabled: true
    enableRedirection: true

  adminPartitions:
    enabled: true
    name: "default"
    # name above is the partition name for servers to reside 	
    service:

  enableConsulNamespaces: true

  peering:
    enabled: true

  tls:
    enabled: true
    enableAutoEncrypt: true
    verify: true

  acls:
   manageSystemACLs: true

server:
  replicas: 3  # 1 for MiniKube or small environments
  bootstrapExpect: 3 # 1 for as above environment
  connect: true
  enabled: true
  exposeGossipAndRPCPorts: true
  metrics:
    enabled: true
    enableAgentMetrics: true
    agentMetricsRetentionTime: '1m'
    enableGatewayMetrics: true


connectInject:
  enabled: true
  default: true                 
  transparentProxy:
    defaultEnabled: true         # Default
  cni:
    enabled: true
  consulNamespaces:
    consulDestinationNamespace: "default"   # Ignored when mirroringK8S is true
    mirroringK8S: true
#   mirroringK8SPrefix: ""
  metrics:
    defaultEnabled: true
    defaultEnableMerging: false  
#    defaultPrometheusScrapePort: 20200
#    defaultPrometheusScrapePath: "/metrics"
#    defaultMergedMetricsPort: 20100

# apiGateway:
#   image: "hashicorp/consul-api-gateway:latest"
#   enabled: true
#   image: hashicorp/consul-api-gateway:0.5.4
#   logLevel: debug
#   managedGatewayClass:
#   enabled: true

terminatingGateways:
  enabled: true
  gateways:
    - name: terminating-gateway
#      extraVolumes:
#      - type: secret
#        name: my-secret
#        items: # optional items array
#          - key: key
#            path: rds-combined-ca-bundle.pem # secret will now mount to /consul/userconfig/my-secret/path

ingressGateways:
  defaults:
    replicas: 1
    service:
      ports:
      - nodePort: null
        port: 443
      - nodePort: null
        port: 8080
      type: 'NodePort' # need to use NodePort as no external connectivity # LoadBalancer
  enabled: true
  gateways:
  - name: ingress-gateway


#ingressGateways:
#  enabled: true
#  gateways:
#    - name: ingress-gateway
#      service:
#        type: 'NodePort'
#        ports:
#          - port: 3000
#          nodePort: 3000
#
#  wanAddress:
#   source: Service
#       annotations: |
#         'service.beta.kubernetes.io/aws-load-balancer-internal': "false"

meshGateway:
  enabled: true
  replicas: 1
# service:
#   enabled: true
    type: 'NodePort'
    ports:
      - port:4000
        nodePort: 4000

# wanAddress:
#   source: Service
#       annotations: |
#         'service.beta.kubernetes.io/aws-load-balancer-internal': "false"

controller:
  enabled: true

ui:
  enabled: true
  metrics:
    enabled: true # by default, this inherits from the value global.metrics.enabled
  service:
    enabled: true
    type: NodePort

prometheus:
 enabled: true
