global:
  enabled: true
  name: consul
# apiVersion: v2
  datacenter: dc1
  image: hashicorp/consul-enterprise:1.14.4-ent
  imageEnvoy: "envoyproxy/envoy-alpine:v1.20.4"
# imageK8S: docker.mirror.hashicorp.services/hashicorp/consul-k8s-control-plane:1.0.2
  imageConsulDataplane: "hashicorp/consul-dataplane:1.0.0"
  enterpriseLicense:
    secretName: consul-ent-license
    secretKey: key

  adminPartitions:
    enabled: true
    name: "default"
    # name above is the partition name for servers to reside 	
#   service:
#     type: LoadBalancer

  enableConsulNamespaces: true

  peering:
    enabled: true

# gossipEncryption:
#   autoGenerate: true

  tls:
    enabled: true
#   enableAutoEncrypt: true
    verify: true

  acls:
   manageSystemACLs: true

server:
  replicas: 3 # 1 for MiniKube and small environment
  bootstrapExpect: 3 # 1 for MiniKube and small environment
  exposeGossipAndRPCPorts: true

  extraConfig: |
    {
      "log_level": "TRACE"
    }

  metrics:
    enabled: true
    enableAgentMetrics: true
    agentMetricsRetentionTime: '1m'


connectInject:
  enabled: true

ingressGateways:
  enabled: true
  gateways:
    - name: ingress-gateway
      service:
        type: 'LoadBalancer'
# wanAddress:
#   source: Service
#       annotations: |
#         'service.beta.kubernetes.io/aws-load-balancer-internal': "false"

meshGateway:
  enabled: true
  replicas: 1
  service:
    enabled: true
    type: 'LoadBalancer'
#  wanAddress:
#    source: Service
#       annotations: |
#         'service.beta.kubernetes.io/aws-load-balancer-internal': "false"

metrics:
  enabled: true
  provider: "prometheus"
  baseURL: http://prometheus-server

controller:
  enabled: true

ui:
  enabled: true
  service:
    enabled: true
    type: LoadBalancer

prometheus:
 enabled: true
