global:
  name: consul
  enabled: false
  image: hashicorp/consul-enterprise:1.17.1-ent
  imageConsulDataplane: "hashicorp/consul-dataplane:1.2.1"
  logLevel: "debug"

  enterpriseLicense:
    secretName: consul-ent-license
    secretKey: key

  dns:
    enabled: true
    enableRedirection: true

  adminPartitions:
    enabled: true
    name: tenant-2

  enableConsulNamespaces: true

  tls:
    enabled: true
    caCert:
      secretName: consul-ca-cert 
      secretKey: tls.crt
    caKey:
      secretName: consul-ca-key 
      secretKey: tls.key

  acls:
    manageSystemACLs: true
    bootstrapToken:
      secretName: consul-partitions-acl-token 
      secretKey: token

# client:
#  enabled: false
#  grpc: true

externalServers:
  enabled: true
  hosts: [ab50a4cc9bfd84dfab0ea6c34cfced8f-951434048.eu-west-1.elb.amazonaws.com] ###### this is your primary K8 expose servers LB ---> kubectl get services -n consul
  tlsServerName: server.dc1.consul                                                ###### match your consul DC name correctly to this 
  k8sAuthMethodHost: https://C637ADFBC7E786F56A70BFA0B9E924D8.yl4.eu-west-1.eks.amazonaws.com ##### this is your client Kubernetes control plane ----> kubectl cluster-info  copy this address
  
controller: 
  enabled: true

metrics:
    defaultEnabled: true
    defaultEnableMerging: true
    defaultPrometheusScrapePort: 20200
    defaultPrometheusScrapePath: "/metrics"
    defaultMergedMetricsPort: 20100
    agentMetricsRetentionTime: '1m'
    enableGatewayMetrics: true

connectInject:
  enabled: true
  default: true                
  transparentProxy:
    defaultEnabled: true         # Default
  cni:
    enabled: true
    logLevel: "debug"
# envoyExtraArgs: "--log-level debug"
  metrics:
    defaultEnabled: true
    defaultEnableMerging: false
    defaultPrometheusScrapePort: 20200
    defaultPrometheusScrapePath: "/metrics"
    defaultMergedMetricsPort: 20100
    
terminatingGateways:
  enabled: true

ingressGateways:
  enabled: true
  gateways:
    - name: ingress-gateway
      service:
        type: 'LoadBalancer'
        ports:
          - port: 8080
  wanAddress:
    source: Service
#       annotations: |
#         'service.beta.kubernetes.io/aws-load-balancer-internal': "false"


meshGateway:
  enabled: true
  replicas: 1
# service:
#   enabled: true
#   type: 'LoadBalancer'
# wanAddress:
#   source: Service

prometheus:
 enabled: true
