# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    myapp: dcanadillas-demo
    tier: front
spec:
  selector:
    myapp: dcanadillas-demo
    tier: front
  ports:
  - protocol: TCP
    port: 8080
    targetPort: http
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend
  labels:
    app: dcanadillas-demo
    tier: front
