# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

# This file configures the hello-world app which serves public web traffic.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: jase-demo
    myapp: jase-demo
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      myapp: jase-demo
      tier: backend
  template:
    metadata:
      labels:
        app: jase-demo
        myapp: jase-demo
        tier: backend
      annotations:
        consul.hashicorp.com/connect-inject: "true"
        consul.hashicorp.com/connect-service: "backend"
    spec:
      serviceAccount: backend
      containers:
      - name: backend
        image: hcdcanadillas/pydemo-back:v1.1-amd64
        imagePullPolicy: Always
        ports:
          - name: http
            containerPort: 8080
        env:
          # %{ for k,v in entrypoint.env }
          # - name: ${k}
          #   value: "${v}"
          # %{ endfor }
          - name: PORT
            value: "8080"
