apiVersion: consul.hashicorp.com/v1alpha1
kind: ExportedServices
metadata:
  name: tenant-1 ## The name of the partition containing the service
spec:
  services:
  - name: mesh-gateway ## to main DC1 (eg DC1) default partition
    consumers:
    - partition: default
  - name: backend ## The name of the service you want to export
    namespace: default
    consumers:
    - partition: default ## The name of the partition that receives the service
