# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

apiVersion: consul.hashicorp.com/v1alpha1
kind: ExportedServices
metadata:
  name: default ## The name of the partition containing the service
spec:
  services:
  - name: mesh-gateway ## The name of the service you want to export (from main DC to partition)
    consumers:
    - partition: tenant-1 The name of the partition that receives the service
