global:
  enabled: true
  name: consul
  apiVersion: v2
  datacenter: dc2
  image: hashicorp/consul-enterprise:1.15.3-ent
  imageConsulDataplane: "hashicorp/consul-dataplane:1.1.0"
  logLevel: "debug"
  enterpriseLicense:
    secretName: consul-ent-license
    secretKey: key

  adminPartitions:
    enabled: true
    name: "default"
    # name above is the partition name for servers to reside 	
    service:

  enableConsulNamespaces: true

  peering:
    enabled: true

  tls:
    enabled: true
    enableAutoEncrypt: true
    verify: true

  acls:
   manageSystemACLs: true

server:
  replicas: 3  # 1 for MiniKube or small environments
  bootstrapExpect: 3 # 1 for as above environment
  connect: true
  enabled: true
  exposeGossipAndRPCPorts: true
  metrics:
    enabled: true
    enableAgentMetrics: true
    agentMetricsRetentionTime: '1m'
    enableGatewayMetrics: true

connectInject:
  enabled: true
  default: true                 
  transparentProxy:
    defaultEnabled: true         # Default
  consulNamespaces:
    consulDestinationNamespace: "default"   # Ignored when mirroringK8S is true
    mirroringK8S: true
#   mirroringK8SPrefix: ""
  metrics:
    defaultEnabled: true
    defaultEnableMerging: false  
  metrics:
    defaultEnabled: true
    defaultEnableMerging: false
#    defaultPrometheusScrapePort: 20200
#    defaultPrometheusScrapePath: "/metrics"
#    defaultMergedMetricsPort: 20100

terminatingGateways:
  enabled: true
  
ingressGateways:
  enabled: true
  gateways:
    - name: ingress-gateway
      service:
        type: 'LoadBalancer'
  wanAddress:
    source: Service
#       annotations: |
#         'service.beta.kubernetes.io/aws-load-balancer-internal': "false"

meshGateway:
  enabled: true
  replicas: 1
# service:
#   enabled: true
#   type: 'LoadBalancer'
# wanAddress:
#   source: Service
#       annotations: |
#         'service.beta.kubernetes.io/aws-load-balancer-internal': "false"

metrics:
  enabled: true
  
controller:
  enabled: true

ui:
  enabled: true
  metrics:
    enabled: true # by default, this inherits from the value global.metrics.enabled
    provider: "prometheus"
    baseURL: http://prometheus-server
  service:
    enabled: true
    type: LoadBalancer
    

prometheus:
 enabled: true
