# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

# Mock Counting Backend
apiVersion: v1
kind: Service
metadata:
  name: counting
spec:
  selector:
    app: counting
  ports:
  - name: http
    protocol: TCP
    port: 9001
    targetPort: 9001
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: counting
---
# deployment for counting
apiVersion: apps/v1
kind: Deployment
metadata:
  name: counting
  labels:
    app: counting
spec:
  replicas: 1
  selector:
    matchLabels:
      app: counting
  template:
    metadata:
      labels:
        app: counting
      annotations:
        "consul.hashicorp.com/connect-inject": "true"
        "consul.hashicorp.com/transparent-proxy": "false"
        metrics.dynatrace.com/port: '9100'
        metrics.dynatrace.com/scrape: 'true'
        metrics.dynatrace.com/secure: 'true'
        metrics.dynatrace.com/path: '/stats/prometheus'

    spec:
      serviceAccountName: counting
      containers:
      - name: counting
        image: hashicorp/http-echo
        ports:
        - containerPort: 9001
        args:
        - -listen=0.0.0.0:9001
        - -text={"count":9998,"hostname":"mock-counting-service --- Tenant1"}
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: counting
spec:
  protocol: "tcp"
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceResolver
metadata:
  name: counting
spec:
  connectTimeout: 10s
