apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: counting-allow-partition-tenant-1
spec:
  destination:
    name: counting     # in partion called partition tenant-1
  sources:
   - name: dashboard
     action: allow
     partition: "default"  # dashboard in default admin partition
