gcp_region = "europe-west1"
gcp_project = "hc-6cd88f9253634329b6aabd42f1e"
node_type = "n1-standard-2"
gcp_zones = ["europe-west1-c","europe-west1-b"]
gke_cluster = "jaseb-test"
numnodes = 3
regional_k8s = false
owner = "jbroadbent"
config_bucket = ""
default_gke = true
default_network = false
k8s_version="1.22"
numclusters = 2
