global:
  name: consul
  enabled: false
  enableConsulNamespaces: true
  image: hashicorp/consul-enterprise:1.14.4-ent
  adminPartitions:
    enabled: true
    name: partition-test
  tls:
    enabled: true
    caCert:
      secretName: consul-ca-cert 
      secretKey: tls.crt
    caKey:
      secretName: consul-ca-key 
      secretKey: tls.key
  acls:
    manageSystemACLs: true
    bootstrapToken:
      secretName: consul-partitions-acl-token 
      secretKey: token
  enterpriseLicense:
    secretName: consul-ent-license
    secretKey: key
externalServers:
  enabled: true
  hosts: ["a6e62e135176b4c27807ecfd18dd681c-1732411789.us-east-2.elb.amazonaws.com"] 
  tlsServerName: server.dc1.consul
  k8sAuthMethodHost: https://6FA8E20A2D3D90DC7DFC6B39B761BE52.sk1.us-east-2.eks.amazonaws.com

controller: 
  enabled: true

meshGateway:
  enabled: true
  replicas: 1
  service:
    enabled: true
    type: 'LoadBalancer'
  wanAddress:
    source: Service

