apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceResolver
metadata:
  name: counting
  namespace: default
spec:
  connectTimeout: 15s
  failover:
    '*':
      targets:
      - service: "counting"
      - namespace: "default"
      - partition: "partition-test"
