global:
# name: consul
  enabled: false
  image: hashicorp/consul-enterprise:1.14.4-ent
  enterpriseLicense:
    secretName: consul-ent-license
    secretKey: key
 
  adminPartitions:
    enabled: true
    name: partition-test

  enableConsulNamespaces: true

  tls:
    enabled: true
    caCert:
      secretName: consul-consul-ca-cert 
      secretKey: tls.crt
    caKey:
      secretName: consul-consul-ca-key 
      secretKey: tls.key

  acls:
    manageSystemACLs: true
    bootstrapToken:
      secretName: consul-consul-partitions-acl-token 
      secretKey: token

externalServers:
  enabled: true
  hosts: [a1fecfc8ccdd74b37b5273d7da904e79-1244336522.us-east-2.elb.amazonaws.com]
  tlsServerName: server.dc1.consul
  k8sAuthMethodHost: https://6FA8E20A2D3D90DC7DFC6B39B761BE52.sk1.us-east-2.eks.amazonaws.com
  
controller: 
  enabled: true

meshGateway:
  enabled: true
  replicas: 1
# service:
#   enabled: true
#   type: 'LoadBalancer'
# wanAddress:
#   source: Service
