global:
  name: consul
  enabled: false
  image: hashicorp/consul-enterprise:1.14.4-ent
  logLevel: "debug"
  enterpriseLicense:
    secretName: consul-ent-license
    secretKey: key
 
  adminPartitions:
    enabled: true
    name: tenant-1

  enableConsulNamespaces: true

  tls:
    enabled: true
    caCert:
      secretName: consul-ca-cert 
      secretKey: tls.crt
    caKey:
      secretName: consul-ca-key 
      secretKey: tls.key

  acls:
    manageSystemACLs: true
    bootstrapToken:
      secretName: consul-partitions-acl-token 
      secretKey: token

# client:
#  enabled: false
#  grpc: true

externalServers:
  enabled: true
  hosts: [ab50a4cc9bfd84dfab0ea6c34cfced8f-951434048.eu-west-1.elb.amazonaws.com]
  tlsServerName: server.dc1.consul
  k8sAuthMethodHost: https://C637ADFBC7E786F56A70BFA0B9E924D8.yl4.eu-west-1.eks.amazonaws.com
  
controller: 
  enabled: true

connectInject:
  enabled: true
  default: true                
  transparentProxy:
    defaultEnabled: true         # Default
    logLevel: "debug"
# envoyExtraArgs: "--log-level debug"
  metrics:
    defaultEnabled: true
    defaultEnableMerging: true

ingressGateways:
  enabled: true
  gateways:
    - name: ingress-gateway
      service:
        type: 'LoadBalancer'
  wanAddress:
    source: Service
#       annotations: |
#         'service.beta.kubernetes.io/aws-load-balancer-internal': "false"

        
# wanAddress:
#   source: Service
#       annotations: |
#         'service.beta.kubernetes.io/aws-load-balancer-internal': "false"

meshGateway:
  enabled: true
  replicas: 1
# service:
#   enabled: true
#   type: 'LoadBalancer'
# wanAddress:
#   source: Service
