# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

apiVersion: consul.hashicorp.com/v1alpha1
kind: ExportedServices
metadata:
  name: tenant-1
spec:
  services:
  - name: mesh-gateway
    consumers:
    - partition: default
  - name: backend
    namespace: default
    consumers:
    - partition: default
