# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

global:
  name: consul
  datacenter: dc1
  image: hashicorp/consul-enterprise:1.10.3-ent  
  enableConsulNamespaces: true  
  acls:
    createReplicationToken: true
    manageSystemACLs: true  

  metrics:
    enabled: true

meshGateway:
  enabled: true
  replicas: 1
  service:
    enabled: true
    type: 'NodePort'
    nodePort: 30200
  wanAddress:
    source: Service
server:
  replicas: 1
  enterpriseLicense:
    secretKey: key
    secretName: consul-ent-license
  connect: true
  enabled: true
ui:
  enabled: true
  service:
    type: 'NodePort'

metrics:
    enabled: true
    provider: "prometheus"
    baseURL: http://prometheus-server

connectInject:
  enabled: true
  default: true
  consulNamespaces:
    mirroringK8S: true
    mirroringK8SPrefix: k8s-
controller:
  enabled: true
syncCatalog:
  enabled: true
  k8sDenyNamespaces: ["kube-system", "kube-node-lease", "default", "kube-public", "consul"]
  consulNamespaces:
    mirroringK8S: true
    mirroringK8SPrefix: k8s-


prometheus:
  enabled: true